#include <TTree.h>
#include <TFile.h>

#include <iostream>
#include <fstream>

#include "facilities/Timestamp.h"
#include "evtUtils/EventClass.h"

int main(int argn, char** argc) {

 
  if (argn != 3) {
    std::cerr << "Usage: MakeEventClassHtml.exe <xmlFile> <outFile>" << std::endl;
    return 1;
  }

  std::string xmlFile(argc[1]);
  evtUtils::EventClass* evtClass = evtUtils::EventClass::loadFromXml(xmlFile);
  if ( evtClass == 0 ) {
    std::cerr << "Failed to load Event class definitions from " << xmlFile << std::endl;
    return 1;
  }
  
  std::string outFileName(argc[2]);

  facilities::Timestamp ts;
  std::string timeStamp = ts.getString();
  timeStamp += " UTC";
  
  std::ofstream os(outFileName.c_str());
  if ( os.fail() ) return false;

  os << "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">" << std::endl;
  os << "<html>" << std::endl;
  os << "  <head>" << std::endl;
  os << "    <title>" << "Event class definitions: version " <<  evtClass->getVersion() << "</title>" << std::endl;
  os << "  </head>" << std::endl;
  os << "  <body>" << std::endl;  
  os << "  <h4>Event class definitions: version " << evtClass->getVersion() << "</h4>" << std::endl;
  os << "  <h6>Generated by evtUtils::MakeEventClassHtml</h6>" << std::endl;
  os << "  <h6>From: " << xmlFile  << "</h6>" << std::endl;    
  os << "  <h6>At: " <<  timeStamp << "</h6>" << std::endl;

  if ( ! evtUtils::EventClass::writeToHtml(*evtClass,os) ){
    std::cerr << "Failed to write html to " << outFileName << std::endl;
    return 1;    
  }

  os << "  </body>" << std::endl;
  os << "</html>" << std::endl;
  os.close();
  
  return 0;
}
