#include <TTree.h>
#include <TFile.h>

#include <iostream>
#include <fstream>

#include "facilities/Timestamp.h"
#include "evtUtils/EventClass.h"

int main(int argn, char** argc) {

 
  if (argn != 3) {
    std::cerr << "Usage: MakeEventClassPyDict.exe <xmlFile> <outFile>" << std::endl;
    return 1;
  }

  std::string xmlFile(argc[1]);
  evtUtils::EventClass* evtClass = evtUtils::EventClass::loadFromXml(xmlFile);
  if ( evtClass == 0 ) {
    std::cerr << "Failed to load Event class definitions from " << xmlFile << std::endl;
    return 1;
  }
  
  std::string outFileName(argc[2]);

  facilities::Timestamp ts;
  std::string timeStamp = ts.getString();
  timeStamp += " UTC";
  
  std::ofstream os(outFileName.c_str());
  if ( os.fail() ) return false;

  os << "\"\"\"" << std::endl;
  os << "@brief Python Dictionary of cuts autogenerated from " << xmlFile << " at " << timeStamp << std::endl;
  os << "\"\"\"" << std::endl;
  os << std::endl;

  std::cout << "Converting xml file " << xmlFile << " to python dictionary " << outFileName << std::endl;

  evtClass->writePythonDict(os);
  os.close();
  
  return 0;
}
